---
title: Hoponaplane
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Hop on a plane
description: Helpfull tips, advice and Itineraries for places around the world.
meta_description: Hop on a plane test
logo: assets/images/logo.png
favicon: assets/images/logo.png
paginate: 15
baseurl: "/hoponaplane"
google_analytics: UA-46278016-1
disqus: demowebsite
mailchimp-list: https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: Author of Mediumish, a Bootstrap Medium styled template available
      for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template
      demo.
  john:
    name: John
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: This is the author box. Write a short description of the author here.
      You are currently previewing Mediumish demo, a Jekyll template compatible with
      Github pages.
  rich:
<<<<<<< HEAD
        name: Rich
        display_name: Rich
        gravatar: b1cc14991db7a456fcd761680bbc8f81
        email: rourkie@gmail.com
        web: https://www.richardallen.co.uk
        description: "Another test."
    
# Plugins
=======
    name: Richard
    dispplay_name: Rich
    gravatar: 
    email: rourkie@gmail.com
    web: https://www.richardallen.co.uk
    description: Another test.
>>>>>>> 25e24c2acd5e74f5f2ca9a270d5d955f19d75130
plugins:
- jekyll-paginate
- jekyll-archives
jekyll-archives:
  enabled:
  - categories
  layout: archive
  permalinks:
<<<<<<< HEAD
    category: '/:name/:title'



# Other
=======
    category: "/category/:name/"
>>>>>>> 25e24c2acd5e74f5f2ca9a270d5d955f19d75130
markdown: kramdown
highlighter: rouge
